from libnum import ecc
import sys

"""
Script to find the first 5 points of the elliptic curve y^2 = x^3 + 7 (mod 89)
"""

# y^2 = x^3 + ax + b (mod p)
a = 0
b = 7
p = 89


if len(sys.argv) > 1:
    a = int(sys.argv[1])
if len(sys.argv) > 2:
    b = int(sys.argv[2])
if len(sys.argv) > 3:
    p = int(sys.argv[3])

c = ecc.Curve(a, b, p)
print("y^2 = x^3 + %dx+%d (mod %d)\n" % (a, b, p))

point = c.find_points_in_range(1, 5)

# Since the nature of find_points_in_range we need to print the first 5 points (6 are generated by the function)
print(point[:5])

